# Generated by Django 5.1.6 on 2025-03-12 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0007_customuser_created_at_alter_customuser_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 10, 34, 11, 160430, tzinfo=datetime.timezone.utc)),
        ),
    ]
